---
driver:
  name: docker

platforms:
    - name: ubuntu-16.04

use_sudo: false

provisioner:
  name: chef_solo
  data_bags_path: './test/integration/data_bags/'
  solo_rb:
    environment: test

suites:
  - name: default
    run_list:
      - recipe[hangops-jobbot::default]
