language: ruby
notifications:
  email: false
  slack:
    secure: LiuCaSXhz0clGvt6daPWowfOjMatF5LS50zlo9PlXjdArVNVkq3dpEGh6O0isvyzqUm34UNw4Gqqug4pVSjWr1A4tgryDtBwLGsxJxMYc5XweEek6mDazR15Q7mdmdXApjn9jcB47A7uEKoT9UR39HxvZQVSrNN0yGIjZdSb/CqXETvo2FZ6cL4fF4UE7IwoL5/+KKlhn9PmABMPEx0tjrGfhCOHNNdv69kB3tAsdJQoZpiiIxKnsuJ4a1o5viy2J2hGG67nkTUYGnFwtRAlOn+QbUNZ2Mc3YNyB10eZ9rjls6ukRbiOVUD3fL9Hr3lRfs8kOTlrK2eUluFzc+maCH2MChsINsJev0lT7/HVZaJgG9RTuxOhZDvy6iZOhIH0W6Ofc1kbTos1oD2yys6/MmablAOIoJMx91QmaZMtFLC/o+iAd+ozJy4eY+YYJiySFniNcxq6lpc2QBF6ct36mibNqyCeU3NrBzyih8C1v8MBx91WTbwLpOh/pOvuB7Ap89DNAHeIeppYQ1yBCtRu8hbksWToiwxQVkXXJRMz98G/72TJ22naA9OsV0CLyTeKXnOgKXW73RR4zxyx/9o4hR36vnZ8cEVocYUWAGmHfrk8CzInLhzmogUZhlnyMHZjoz3SWQS4+FxgFdsZFLkwzl3U7luesBaOcC7bubtGWfs=
sudo: required

dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

bundler_args: --without='vagrant'

install:
  - cd ./cookbooks/hangops-jobbot
  - gem install bundler

branches:
  only:
    - master

services: docker

env:
  - INSTANCE=default-ubuntu-1604

before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version
  - pwd

script:
  # Fake 'localhost' to go back to docker host
  - sed -e '/localhost/d' /etc/hosts > /var/tmp/hosts.new
  - cp /var/tmp/hosts.new /etc/hosts
  - echo "$(ip route | grep default | awk '{print $3}') localhost" >> /etc/hosts
  # Full Index to make some tetchy gems work
  - bundle --full-index
  # Run test suite
  - bundle exec rake travis
