language: ruby
notifications:
  email: false
  slack:
    secure: LiuCaSXhz0clGvt6daPWowfOjMatF5LS50zlo9PlXjdArVNVkq3dpEGh6O0isvyzqUm34UNw4Gqqug4pVSjWr1A4tgryDtBwLGsxJxMYc5XweEek6mDazR15Q7mdmdXApjn9jcB47A7uEKoT9UR39HxvZQVSrNN0yGIjZdSb/CqXETvo2FZ6cL4fF4UE7IwoL5/+KKlhn9PmABMPEx0tjrGfhCOHNNdv69kB3tAsdJQoZpiiIxKnsuJ4a1o5viy2J2hGG67nkTUYGnFwtRAlOn+QbUNZ2Mc3YNyB10eZ9rjls6ukRbiOVUD3fL9Hr3lRfs8kOTlrK2eUluFzc+maCH2MChsINsJev0lT7/HVZaJgG9RTuxOhZDvy6iZOhIH0W6Ofc1kbTos1oD2yys6/MmablAOIoJMx91QmaZMtFLC/o+iAd+ozJy4eY+YYJiySFniNcxq6lpc2QBF6ct36mibNqyCeU3NrBzyih8C1v8MBx91WTbwLpOh/pOvuB7Ap89DNAHeIeppYQ1yBCtRu8hbksWToiwxQVkXXJRMz98G/72TJ22naA9OsV0CLyTeKXnOgKXW73RR4zxyx/9o4hR36vnZ8cEVocYUWAGmHfrk8CzInLhzmogUZhlnyMHZjoz3SWQS4+FxgFdsZFLkwzl3U7luesBaOcC7bubtGWfs=
sudo: required

dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

bundler_args: --without='vagrant'

install:
  - cd ./cookbooks/hangops-jobbot
  - gem install bundler

branches:
  only:
    - master

services: docker

env:
  global:
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  #   via the "travis encrypt" command using the project repo's public key
  - secure: "UsxtdhtRk9P2Jvi6JbjmVRKBjvttOZikNZAATO7tr2twsU6376VLXhJ3jHb4gNmq8/bDOhXWPzSIUFVTUU9jNdfcUnp0Xiuo89UTdKAti1t4fvU/vCqentmt0qJx1JBJnzO9asI0hLfwyP8oGlXdushMPWNUt72TN689PsFdqoZ9Jp7QQ5dF4JvUVth1LlCnx7N6gVtfYvqdj2XmPF2EfBfqe9GnJUGLStmJb9Ma0gW1xCYBy/GqBWORE97ITnVkAcZAdKw8WypA7ZF3gbU0ce15iL8rElHm3m8KF0g3e7aLm1X0QBljk59fc28R83xXhsQ0ZyVXUg8Exos9xQv07C55xQV0rX0WSeRHC7xoJIavNBmqqSNNQ2duFXsOMQZQG5M6khMvGNWhemITwyK5AHMebMPMrHXlZmI/gsRUvVe/7pShSEvrFESdF6jMAZtycfobwk22Qc5tUl0/u/056ic4hqu/t52ww2UIKf7o6nc484FMYZ6Z8ZlHXE4VjqqS6akgQhnkZTbsDWfLiUXYCHv6wSi1IAxiHG8oDz7oYfQvzmdnBDhmEfFW4IXEHAjXXHq3C4gfJAdVv/kQcUgjCeHugc5MwR2rOcEl9QnnaEywuip88Q00EeIpu274sdOTBfm9nF9aHS5MWaKGWfZ/ZJsJuWgAqu/As="
  - INSTANCE=default-ubuntu-1604

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version
  - pwd

script:
  # Full Index to make some tetchy gems work
  - bundle --full-index
  # Run test suite
  - bundle exec rake travis

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master

#  after_success: "./deploy.sh"

addons:
  coverity_scan:
    project:
      name: "rrxtns/hangops-jobbot"
      description: "A bot for Hangops #job_board channel"
    notification_email: sntxrr+github@gmail.com
    build_command_prepend: ""
    build_command:   ""
    branch_pattern: coverity_scan
    